### ISSUE TITLE
feat(deploy): Railway へのデプロイ設定

### ISSUE THREAD

**Issue by siropaca** [siropaca/white-flask#6]
## 概要

White Flask を Railway.com にデプロイし、本番環境を構築します。モノレポ構造に対応した 3 つのサービス（blog, admin, backend）と PostgreSQL データベースを設定します。

## 現状分析

現在のプロジェクト構造：
- `apps/blog` - SvelteKit フロントエンド（ポート 3000）
- `apps/admin` - Next.js 管理画面（ポート 3001）
- `apps/backend` - GraphQL API（ポート 4000）
- pnpm workspaces を使用したモノレポ構成
- Docker Compose で PostgreSQL を開発環境で使用

Railway へのデプロイに必要な設定・構成が未整備の状態です。

## 実装手順

1. **Railway プロジェクトの作成**
   ```bash
   # Railway CLI のインストール（未インストールの場合）
   npm install -g @railway/cli
   
   # Railway にログイン
   railway login
   
   # プロジェクトの初期化
   railway init
   ```

2. **サービスの作成**
   - PostgreSQL データベース
   - Blog フロントエンド（SvelteKit）
   - Admin パネル（Next.js）
   - Backend API（GraphQL）

3. **railway.toml の作成**
   各アプリケーションにデプロイ設定ファイルを作成：
   - `apps/blog/railway.toml`
   - `apps/admin/railway.toml`
   - `apps/backend/railway.toml`

4. **環境変数の設定**
   Railway ダッシュボードで各サービスに環境変数を設定

5. **GitHub Actions の設定**
   `.github/workflows/railway-deploy.yml` を作成

### apps/blog/railway.toml
```toml
[build]
builder = "nixpacks"
buildCommand = "cd ../.. && pnpm install --frozen-lockfile && cd apps/blog && pnpm build"

[deploy]
startCommand = "cd apps/blog && pnpm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

[[services]]
name = "blog"
```

### apps/admin/railway.toml
```toml
[build]
builder = "nixpacks"
buildCommand = "cd ../.. && pnpm install --frozen-lockfile && cd apps/admin && pnpm build"

[deploy]
startCommand = "cd apps/admin && pnpm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

[[services]]
name = "admin"
```

### apps/backend/railway.toml
```toml
[build]
builder = "nixpacks"
buildCommand = "cd ../.. && pnpm install --frozen-lockfile && cd apps/backend && pnpm prisma generate && pnpm build"

[deploy]
startCommand = "cd apps/backend && pnpm prisma migrate deploy && pnpm start"
healthcheckPath = "/graphql"
healthcheckTimeout = 300
restartPolicyType = "always"

[[services]]
name = "backend"
```

### .github/workflows/railway-deploy.yml
```yaml
name: Deploy to Railway

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Railway CLI
        run: npm install -g @railway/cli
      
      - name: Deploy Blog
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service blog --detach
      
      - name: Deploy Admin
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service admin --detach
      
      - name: Deploy Backend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service backend --detach
```

### Blog サービス
```env
PUBLIC_GRAPHQL_ENDPOINT=https://backend.railway.app/graphql
NODE_ENV=production
```

### Admin サービス
```env
NEXT_PUBLIC_GRAPHQL_ENDPOINT=https://backend.railway.app/graphql
NODE_ENV=production
```

### Backend サービス
```env
DATABASE_URL=${{POSTGRES.DATABASE_URL}}
NODE_ENV=production
PORT=4000
```

### PostgreSQL サービス
Railway が自動的に以下を提供：
- `DATABASE_URL`
- `POSTGRES_USER`
- `POSTGRES_PASSWORD`
- `POSTGRES_DB`

## デプロイ構成

```
Railway プロジェクト
├── blog (SvelteKit)
│   ├── カスタムドメイン: blog.example.com
│   └── Railway 提供ドメイン: blog-production.up.railway.app
├── admin (Next.js)
│   ├── カスタムドメイン: admin.example.com
│   └── Railway 提供ドメイン: admin-production.up.railway.app
├── backend (GraphQL API)
│   ├── カスタムドメイン: api.example.com
│   └── Railway 提供ドメイン: backend-production.up.railway.app
└── PostgreSQL
    └── 内部ネットワーク経由でのみアクセス可能
```

### ビルド設定の考慮事項
- Node.js バージョン: 24.2.0（mise 設定と一致）
- pnpm バージョン: package.json の packageManager フィールドから自動検出
- モノレポのルートから依存関係をインストール
- 各サービスは独自のビルド・起動コマンドを実行

### ネットワーク設定
- すべてのサービスは Railway の内部ネットワークで通信
- Backend サービスは内部ドメイン名で参照（例: `http://backend.railway.internal:4000`）
- 外部からのアクセスは Railway が提供する HTTPS ドメインを使用

## 完了条件

- [ ] Railway プロジェクトの作成完了
- [ ] 4 つのサービス（blog, admin, backend, postgres）の作成
- [ ] 各サービスの railway.toml 設定ファイルの作成
- [ ] 環境変数の設定完了
- [ ] GitHub Actions ワークフローの設定
- [ ] 初回デプロイの成功
- [ ] データベースマイグレーションの実行確認
- [ ] 各サービスのヘルスチェック通過
- [ ] Railway 提供ドメインでの動作確認
- [ ] サービス間の通信確認（フロントエンド → API → DB）
